spring.application.name=Examen


### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true
spring.datasource.username=Sergera
spring.datasource.password=159753159753
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/Examen
server.port=8089




